"""
Django settings for webgis_dss project.

Generated by 'django-admin startproject' using Django 4.2.23.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-s39hy9ylg*lf(v=6@0iufb-+ta0xkj0pe_d0$lme0ff2e$m)%d"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    'django.contrib.gis', 
    'map_app',            
    'leaflet',
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "webgis_dss.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "webgis_dss.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.contrib.gis.db.backends.postgis', # Bắt buộc dùng postgis
        'NAME': 'webgis_db',       # Tên DB bạn vừa tạo bên pgAdmin
        'USER': 'postgres',        # Tên đăng nhập mặc định
        'PASSWORD': '123',      # Mật khẩu bạn vừa đặt (Nhớ sửa nếu khác)
        'HOST': 'localhost',
        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
import os
import sys

# --- CẤU HÌNH GDAL TỰ ĐỘNG CHO CẢ NHÓM (LEGION & ASUS) ---
if os.name == 'nt':
    # 1. Tự động lấy đường dẫn môi trường Anaconda đang chạy
    # Trên máy Legion nó sẽ tự ra: C:\Users\Legion\anaconda3\envs\webgis_env
    # Trên máy ASUS nó sẽ tự ra: C:\Users\ASUS\anaconda3\envs\webgis_env
    VENV_BASE = sys.prefix 
    
    # 2. Định nghĩa thư mục bin chứa file dll
    LIBRARY_BIN = os.path.join(VENV_BASE, 'Library', 'bin')
    
    # 3. Thêm vào biến môi trường (để Windows tìm thấy file)
    os.environ['PATH'] = LIBRARY_BIN + ';' + os.environ['PATH']
    
    # 4. TỰ ĐỘNG QUÉT TÌM FILE GDAL (Không cần quan tâm tên là gdal.dll hay gdal304.dll)
    GDAL_LIBRARY_PATH = None
    if os.path.exists(LIBRARY_BIN):
        for filename in os.listdir(LIBRARY_BIN):
            # Tìm file bắt đầu bằng 'gdal', đuôi '.dll' và KHÔNG có chữ 'wrap'
            if filename.startswith('gdal') and filename.endswith('.dll') and 'wrap' not in filename:
                GDAL_LIBRARY_PATH = os.path.join(LIBRARY_BIN, filename)
                print(f"--> ĐÃ TỰ ĐỘNG NHẬN DIỆN GDAL TẠI: {GDAL_LIBRARY_PATH}")
                break
    
    # 5. Cấu hình các dữ liệu phụ trợ
    os.environ['GDAL_DATA'] = os.path.join(VENV_BASE, 'Library', 'share', 'gdal')
    os.environ['PROJ_LIB'] = os.path.join(VENV_BASE, 'Library', 'share', 'proj')

    if not GDAL_LIBRARY_PATH:
        print("!!! CẢNH BÁO: Không tìm thấy file gdal trong thư mục Library/bin !!!")

# Cấu hình lưu trữ file ảnh
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'