# Generated by Django 4.2.23 on 2026-04-15 04:55

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NhaTro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ten_nha",
                    models.CharField(max_length=200, verbose_name="Tên khu nhà trọ"),
                ),
                ("dia_chi", models.CharField(max_length=255)),
                ("location", django.contrib.gis.db.models.fields.PointField(srid=4326)),
                (
                    "hinh_anh",
                    models.ImageField(blank=True, null=True, upload_to="nha_tro/"),
                ),
                (
                    "mo_ta",
                    models.TextField(blank=True, null=True, verbose_name="Mô tả chung"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "favorites",
                    models.ManyToManyField(
                        blank=True,
                        related_name="nha_tro_yeu_thich",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TinTuc",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tieu_de", models.CharField(max_length=200, verbose_name="Tiêu đề")),
                (
                    "hinh_anh",
                    models.ImageField(blank=True, null=True, upload_to="tin_tuc/"),
                ),
                ("noi_dung", models.TextField(verbose_name="Nội dung")),
                ("ngay_dang", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="PhongTro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ten_phong",
                    models.CharField(
                        max_length=50, verbose_name="Số phòng (VD: P.101)"
                    ),
                ),
                ("gia_thue", models.DecimalField(decimal_places=0, max_digits=10)),
                ("dien_tich", models.FloatField(default=20)),
                (
                    "trang_thai",
                    models.CharField(
                        choices=[("trong", "🟢 Còn trống"), ("da_dat", "🔴 Đã đặt")],
                        default="trong",
                        max_length=20,
                    ),
                ),
                (
                    "nha_tro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="danh_sach_phong",
                        to="map_app.nhatro",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="KhieuNai",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tieu_de", models.CharField(max_length=200)),
                ("noi_dung", models.TextField()),
                (
                    "trang_thai",
                    models.CharField(
                        choices=[
                            ("moi", "Mới tiếp nhận"),
                            ("dang_xu_ly", "Đang xử lý"),
                            ("da_xong", "Đã giải quyết"),
                        ],
                        default="moi",
                        max_length=20,
                    ),
                ),
                ("ngay_tao", models.DateTimeField(auto_now_add=True)),
                (
                    "nguoi_gui",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HinhAnhTinTuc",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hinh_anh", models.ImageField(upload_to="tin_tuc_phu/")),
                (
                    "tin_tuc",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="danh_sach_anh_tin",
                        to="map_app.tintuc",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HinhAnhNhaTro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hinh_anh", models.ImageField(upload_to="nhatro_gallery/")),
                (
                    "nha_tro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="danh_sach_anh",
                        to="map_app.nhatro",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DonDatPhong",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ngay_tao", models.DateTimeField(auto_now_add=True)),
                ("ngay_don_vao", models.DateField(verbose_name="Ngày dự kiến dọn vào")),
                ("tien_coc", models.DecimalField(decimal_places=0, max_digits=10)),
                (
                    "trang_thai",
                    models.CharField(
                        choices=[
                            ("cho_xac_nhan", "⏳ Chờ xác nhận"),
                            ("da_dat_coc", "✅ Đã đặt cọc"),
                            ("huy", "❌ Đã hủy"),
                        ],
                        default="cho_xac_nhan",
                        max_length=20,
                    ),
                ),
                ("ghi_chu", models.TextField(blank=True, null=True)),
                (
                    "nguoi_thue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "phong",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="map_app.phongtro",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DanhGia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("so_sao", models.IntegerField(default=5)),
                ("noi_dung", models.TextField()),
                ("ngay_tao", models.DateTimeField(auto_now_add=True)),
                (
                    "nguoi_danh_gia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "nha_tro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="danh_sach_danh_gia",
                        to="map_app.nhatro",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="danhgia",
            constraint=models.UniqueConstraint(
                fields=("nha_tro", "nguoi_danh_gia"), name="unique_review_per_user"
            ),
        ),
    ]
