# Generated by Django 4.2.23 on 2026-04-22 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("map_app", "0002_phongtro_hinh_anh"),
    ]

    operations = [
        migrations.AlterField(
            model_name="phongtro",
            name="hinh_anh",
            field=models.ImageField(blank=True, null=True, upload_to="phong_tro/"),
        ),
    ]
