# Generated by Django 4.2.23 on 2026-04-24 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("map_app", "0003_alter_phongtro_hinh_anh"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrangGioiThieu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tieu_de_chinh",
                    models.CharField(
                        default="Về Chúng Tôi",
                        max_length=200,
                        verbose_name="Tiêu đề chính",
                    ),
                ),
                (
                    "mo_ta_ngan",
                    models.TextField(
                        default="Mô tả ngắn hiển thị dưới tiêu đề.",
                        verbose_name="Mô tả ngắn (hero)",
                    ),
                ),
                (
                    "hinh_anh_banner",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="gioi_thieu/",
                        verbose_name="Ảnh banner",
                    ),
                ),
                (
                    "tieu_de_su_menh",
                    models.CharField(
                        default="Sứ Mệnh Của Chúng Tôi",
                        max_length=200,
                        verbose_name="Tiêu đề sứ mệnh",
                    ),
                ),
                (
                    "noi_dung_su_menh",
                    models.TextField(
                        default="Nhập nội dung sứ mệnh tại đây.",
                        verbose_name="Nội dung sứ mệnh",
                    ),
                ),
                (
                    "so_phong",
                    models.IntegerField(default=0, verbose_name="Số phòng trọ"),
                ),
                (
                    "so_sinh_vien",
                    models.IntegerField(default=0, verbose_name="Sinh viên tin dùng"),
                ),
                (
                    "so_quan",
                    models.IntegerField(default=0, verbose_name="Quận/Huyện phủ sóng"),
                ),
                (
                    "so_nam",
                    models.IntegerField(default=0, verbose_name="Năm hoạt động"),
                ),
                (
                    "thanh_vien_1_ten",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Thành viên 1 – Tên"
                    ),
                ),
                (
                    "thanh_vien_1_chuc_vu",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Thành viên 1 – Chức vụ",
                    ),
                ),
                (
                    "thanh_vien_1_anh",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="gioi_thieu/doi_ngu/",
                        verbose_name="Thành viên 1 – Ảnh",
                    ),
                ),
                (
                    "thanh_vien_2_ten",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Thành viên 2 – Tên"
                    ),
                ),
                (
                    "thanh_vien_2_chuc_vu",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Thành viên 2 – Chức vụ",
                    ),
                ),
                (
                    "thanh_vien_2_anh",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="gioi_thieu/doi_ngu/",
                        verbose_name="Thành viên 2 – Ảnh",
                    ),
                ),
                (
                    "thanh_vien_3_ten",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Thành viên 3 – Tên"
                    ),
                ),
                (
                    "thanh_vien_3_chuc_vu",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Thành viên 3 – Chức vụ",
                    ),
                ),
                (
                    "thanh_vien_3_anh",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="gioi_thieu/doi_ngu/",
                        verbose_name="Thành viên 3 – Ảnh",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Email liên hệ"
                    ),
                ),
                (
                    "so_dien_thoai",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Số điện thoại"
                    ),
                ),
                (
                    "dia_chi",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Địa chỉ văn phòng"
                    ),
                ),
                ("facebook", models.URLField(blank=True, verbose_name="Link Facebook")),
                (
                    "zalo",
                    models.CharField(blank=True, max_length=20, verbose_name="Số Zalo"),
                ),
            ],
            options={
                "verbose_name": "Trang Giới Thiệu",
            },
        ),
    ]
