# Generated by Django 4.2.23 on 2026-04-26 12:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("map_app", "0004_tranggioithieu"),
    ]

    operations = [
        migrations.AddField(
            model_name="nhatro",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="nha_tro_so_huu",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Chủ sở hữu",
            ),
        ),
        migrations.CreateModel(
            name="HoSoChuTro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("so_dien_thoai", models.CharField(blank=True, max_length=20)),
                ("dia_chi", models.CharField(blank=True, max_length=255)),
                (
                    "ngay_cap",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Ngày cấp quyền"
                    ),
                ),
                (
                    "ghi_chu",
                    models.TextField(blank=True, verbose_name="Ghi chú của Admin"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ho_so_chu_tro",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Hồ sơ Chủ trọ",
            },
        ),
    ]
