# Generated by Django 4.2.23 on 2026-01-29 11:37

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PhongTro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ten", models.CharField(max_length=200, verbose_name="Tên phòng trọ")),
                ("dia_chi", models.CharField(max_length=500, verbose_name="Địa chỉ")),
                (
                    "gia_thue",
                    models.IntegerField(help_text="VNĐ/tháng", verbose_name="Giá thuê"),
                ),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(
                        srid=4326, verbose_name="Vị trí trên bản đồ"
                    ),
                ),
                ("mo_ta", models.TextField(blank=True, verbose_name="Mô tả chi tiết")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
