# Generated by Django 4.2.23 on 2026-01-29 14:08

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("map_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="phongtro",
            name="dien_tich",
            field=models.IntegerField(default=20, verbose_name="Diện tích (m2)"),
        ),
        migrations.AddField(
            model_name="phongtro",
            name="hinh_anh",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="phong_tro/",
                verbose_name="Hình ảnh thực tế",
            ),
        ),
        migrations.AddField(
            model_name="phongtro",
            name="sdt_lien_he",
            field=models.CharField(
                default="0909000000", max_length=15, verbose_name="SĐT Liên hệ"
            ),
        ),
        migrations.AlterField(
            model_name="phongtro",
            name="dia_chi",
            field=models.CharField(max_length=500, verbose_name="Địa chỉ cụ thể"),
        ),
        migrations.AlterField(
            model_name="phongtro",
            name="gia_thue",
            field=models.IntegerField(verbose_name="Giá (VNĐ/tháng)"),
        ),
        migrations.AlterField(
            model_name="phongtro",
            name="location",
            field=django.contrib.gis.db.models.fields.PointField(
                srid=4326, verbose_name="Vị trí bản đồ"
            ),
        ),
        migrations.AlterField(
            model_name="phongtro",
            name="ten",
            field=models.CharField(max_length=200, verbose_name="Tiêu đề tin đăng"),
        ),
    ]
