# Generated by Django 4.2.23 on 2026-04-15 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("map_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="phongtro",
            name="hinh_anh",
            field=models.ImageField(
                blank=True, null=True, upload_to="phong_tro/", verbose_name="Ảnh phòng"
            ),
        ),
    ]
