# Generated by Django 4.2.23 on 2026-01-30 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("map_app", "0002_phongtro_dien_tich_phongtro_hinh_anh_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TinTuc",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tieu_de",
                    models.CharField(max_length=200, verbose_name="Tiêu đề tin"),
                ),
                (
                    "hinh_anh",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="tintuc/",
                        verbose_name="Hình ảnh",
                    ),
                ),
                (
                    "tom_tat",
                    models.TextField(
                        blank=True, max_length=500, verbose_name="Tóm tắt ngắn"
                    ),
                ),
                ("noi_dung", models.TextField(verbose_name="Nội dung chi tiết")),
                (
                    "ngay_dang",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày đăng"),
                ),
            ],
            options={
                "verbose_name_plural": "Quản lý Tin Tức",
            },
        ),
    ]
