# Generated by Django 4.2.23 on 2026-01-30 15:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("map_app", "0003_tintuc"),
    ]

    operations = [
        migrations.AddField(
            model_name="phongtro",
            name="favorites",
            field=models.ManyToManyField(
                blank=True, related_name="favorite_rooms", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
