# Generated by Django 4.2.23 on 2026-01-30 16:07

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("map_app", "0004_phongtro_favorites"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tintuc",
            options={},
        ),
        migrations.RemoveField(
            model_name="phongtro",
            name="sdt_lien_he",
        ),
        migrations.RemoveField(
            model_name="tintuc",
            name="hinh_anh",
        ),
        migrations.RemoveField(
            model_name="tintuc",
            name="tom_tat",
        ),
        migrations.AlterField(
            model_name="phongtro",
            name="dia_chi",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="phongtro",
            name="dien_tich",
            field=models.FloatField(default=20),
        ),
        migrations.AlterField(
            model_name="phongtro",
            name="gia_thue",
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="phongtro",
            name="hinh_anh",
            field=models.ImageField(blank=True, null=True, upload_to="phong_tro/"),
        ),
        migrations.AlterField(
            model_name="phongtro",
            name="location",
            field=django.contrib.gis.db.models.fields.PointField(srid=4326),
        ),
        migrations.AlterField(
            model_name="phongtro",
            name="mo_ta",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="phongtro",
            name="ten",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="tintuc",
            name="ngay_dang",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="tintuc",
            name="noi_dung",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="tintuc",
            name="tieu_de",
            field=models.CharField(max_length=200),
        ),
    ]
