# Generated by Django 4.2.23 on 2026-02-01 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("map_app", "0005_alter_tintuc_options_remove_phongtro_sdt_lien_he_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tintuc",
            options={
                "verbose_name": "Tin tức",
                "verbose_name_plural": "Quản lý Tin tức",
            },
        ),
        migrations.AddField(
            model_name="tintuc",
            name="hinh_anh",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="tin_tuc/",
                verbose_name="Hình ảnh đại diện",
            ),
        ),
        migrations.AlterField(
            model_name="tintuc",
            name="ngay_dang",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Ngày đăng"),
        ),
        migrations.AlterField(
            model_name="tintuc",
            name="noi_dung",
            field=models.TextField(verbose_name="Nội dung"),
        ),
        migrations.AlterField(
            model_name="tintuc",
            name="tieu_de",
            field=models.CharField(max_length=200, verbose_name="Tiêu đề"),
        ),
    ]
