# Generated by Django 4.2.23 on 2026-02-04 14:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("map_app", "0006_alter_tintuc_options_tintuc_hinh_anh_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DonDatPhong",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ngay_tao", models.DateTimeField(auto_now_add=True)),
                ("ngay_don_vao", models.DateField(verbose_name="Ngày dự kiến dọn vào")),
                ("tien_coc", models.DecimalField(decimal_places=0, max_digits=10)),
                (
                    "trang_thai",
                    models.CharField(
                        choices=[
                            ("cho_xac_nhan", "⏳ Chờ xác nhận"),
                            ("da_coc", "✅ Đã đặt cọc"),
                            ("huy", "❌ Đã hủy"),
                        ],
                        default="cho_xac_nhan",
                        max_length=20,
                    ),
                ),
                ("ghi_chu", models.TextField(blank=True, null=True)),
                (
                    "nguoi_thue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "phong",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="map_app.phongtro",
                    ),
                ),
            ],
        ),
    ]
