# Generated by Django 4.2.23 on 2026-03-20 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("map_app", "0007_dondatphong"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dondatphong",
            name="trang_thai",
            field=models.CharField(
                choices=[
                    ("cho_xac_nhan", "⏳ Chờ xác nhận"),
                    ("da_dat_coc", "✅ Đã đặt cọc"),
                    ("huy", "❌ Đã hủy"),
                ],
                default="cho_xac_nhan",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="HinhAnhPhongTro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hinh_anh", models.ImageField(upload_to="phongtro_gallery/")),
                (
                    "phong",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="danh_sach_anh",
                        to="map_app.phongtro",
                    ),
                ),
            ],
        ),
    ]
