# Generated by Django 4.2.23 on 2026-03-31 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("map_app", "0008_alter_dondatphong_trang_thai_hinhanhphongtro"),
    ]

    operations = [
        migrations.CreateModel(
            name="HinhAnhTinTuc",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hinh_anh", models.ImageField(upload_to="tin_tuc_phu/")),
                (
                    "tin_tuc",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="danh_sach_anh_tin",
                        to="map_app.tintuc",
                    ),
                ),
            ],
        ),
    ]
