# Generated by Django 4.2.23 on 2026-03-31 07:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("map_app", "0009_hinhanhtintuc"),
    ]

    operations = [
        migrations.CreateModel(
            name="KhieuNai",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tieu_de", models.CharField(max_length=200)),
                ("noi_dung", models.TextField()),
                (
                    "trang_thai",
                    models.CharField(
                        choices=[
                            ("moi", "Mới tiếp nhận"),
                            ("dang_xu_ly", "Đang xử lý"),
                            ("da_xong", "Đã giải quyết"),
                        ],
                        default="moi",
                        max_length=20,
                    ),
                ),
                ("ngay_tao", models.DateTimeField(auto_now_add=True)),
                (
                    "nguoi_gui",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DanhGia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("so_sao", models.IntegerField(default=5)),
                ("noi_dung", models.TextField()),
                ("ngay_tao", models.DateTimeField(auto_now_add=True)),
                (
                    "nguoi_danh_gia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "phong",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="danh_sach_danh_gia",
                        to="map_app.phongtro",
                    ),
                ),
            ],
        ),
    ]
