# Generated by Django 4.2.23 on 2026-03-31 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("map_app", "0010_khieunai_danhgia"),
    ]

    operations = [
        migrations.AlterField(
            model_name="phongtro",
            name="mo_ta",
            field=models.TextField(
                blank=True, null=True, verbose_name="Mô tả chi tiết"
            ),
        ),
    ]
